-- New users get a UUID (`@default(uuid())` is generated by Prisma, so the
-- column stays TEXT). Existing cuid ids are replaced here; every foreign key
-- to users.id is ON UPDATE CASCADE, so categories, transactions, refresh
-- tokens and settings follow.
UPDATE "users"
SET "id" = gen_random_uuid()::text
WHERE "id" !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';

-- Issued tokens carry the old id as `sub` and would be rejected anyway;
-- dropping them signs everyone out cleanly.
DELETE FROM "refresh_tokens";
