-- Users, categories and refresh tokens get UUIDs like transactions
-- (`@default(uuid())` is generated by Prisma, so the columns stay TEXT).
-- Existing cuid ids are replaced here; every foreign key to users.id and
-- categories.id is ON UPDATE CASCADE, so the rows that reference them follow.
UPDATE "users"
SET "id" = gen_random_uuid()::text
WHERE "id" !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';

UPDATE "categories"
SET "id" = gen_random_uuid()::text
WHERE "id" !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';

-- Issued tokens carry the old user id as `sub` (and the token id as `jti`)
-- and would be rejected anyway; dropping them signs everyone out cleanly.
DELETE FROM "refresh_tokens";
